# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db-mount:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080

  server:
    image: node:13
    working_dir: /home/node/app
    # environment:
    # - NODE_ENV=production
    volumes:
      - ./:/home/node/app
      - ./init:/bin/init
      - ./config/docker.yaml:/home/node/app/config/local.yaml
    ports:
      - 9081:8080
    command: 'npm run dev'
