apps:
  - script: ./server.js
    append_env_to_name: true
    name: 'Boilerplate'
    instances: 1
    exec_mode: cluster
    env:
      NODE_ENV: development
    env_production:
      NODE_ENV: production
