manifest:
  connections:
    - host: 'localhost'
      port: 8080
      routes:
        cors: true
      router:
        stripTrailingSlash: true
  registrations:
    - plugin: './api'
knex:
  useNullAsDefault: true
  client: 'sqlite3'
  connection:
    filename: './database.sqlite3'
