manifest:
  connections:
    - host: 'localhost'
      port: 8080
      routes:
        cors: true
      router:
        stripTrailingSlash: true
  registrations:
    - plugin: './api'
    - plugin:
        register: 'good'
        options:
          ops:
            interval: 1000
          reporters:
            console:
              - module: 'good-squeeze'
                name: 'Squeeze'
                args:
                - error: '*'
              - module: 'good-console'
              - 'stdout'
knex:
  useNullAsDefault: true
  client: 'sqlite3'
  connection:
    filename: './database.sqlite3'
