manifest:
  register:
    plugins:
      - plugin: 'hapi-swagger'
        options:
          info:
            title: 'Lumberjack'
          grouping: 'tags'
          documentationPath: '/'
knex:
  useNullAsDefault: true
  client: 'sqlite3'
  connection:
    filename: './database.sqlite3'
cookieOptions:
  ttl: 31536000000 # expires a year from today
  encoding: 'none' # we already used JWT to encode
  isSecure: false # can be enabled if the server runs https
  isHttpOnly: false # we validate with http, so has to be false
  clearInvalid: true # remove invalid cookies
  strictHeader: true # don't allow violations of RFC 6265
  path: '/' # set the cookie for all routes
defaultRange:
  rangeStart: 0
  rangeEnd: 30
baseUrl: 'https://www.example.org'
log:
  prettyPrint: true
  level: 'info'
