manifest:
  server:
    address: '0.0.0.0'
    port: 8080
  register:
    plugins:
      - plugin: 'hapi-auth-jwt2'
      - plugin: 'plugins/initAuth'
      - plugin: 'plugins/initPermissions'
      - plugin: './api'
      - plugin: '@hapi/inert'
      - plugin: '@hapi/vision'
      - plugin: 'hapi-swagger'
        options:
          info:
            title: 'Boilerplate'
          grouping: 'tags'
          documentationPath: '/'
      - plugin: '@hapi/good'
        options:
          ops:
            interval: 1000
          reporters:
            console:
              - module: '@hapi/good-squeeze'
                name: 'Squeeze'
                args:
                  - error: '*'
              - module: '@hapi/good-console'
              - 'stdout'
      - plugin: 'blipp'
