manifest:
  registrations:
    - plugin: './api'
    - plugin:
        register: 'good'
        options:
          ops:
            interval: 1000
          reporters:
            console:
              - module: 'good-squeeze'
                name: 'Squeeze'
                args:
                - error: '*'
              - module: 'good-console'
              - 'stdout'
    - plugin:
        register: 'blipp'
    - plugin:
        register: 'hapi-ending'
        options: { enabled: true }
