manifest:
  server:
    address: '0.0.0.0'
    port: 8080
  register:
    plugins:
      - plugin: 'hapi-swagger'
        options:
          info:
            title: 'backend'
          grouping: 'tags'
          documentationPath: '/'
      - plugin: 'blipp'
