knex:
  useNullAsDefault: true
  client: 'sqlite3'
  connection:
    filename: ':memory:'
manifest:
  server:
    autoListen: false
    routes:
      cors:
        origin: 'ignore'
  register:
    plugins:
      - plugin: 'hapi-pino'
        options:
          prettyPrint: true
          level: 'error'
