knex:
  useNullAsDefault: true
  client: 'sqlite3'
  connection:
    filename: ':memory:'
manifest:
  server:
    autoListen: false
    routes:
      cors:
        origin: 'ignore'
jwtSecret: 'secret'
log:
  level: 'warn'
